<?php
$title = 'Produtos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div>
				<table class="table table-striped table-bordered" id="data">
				    <thead>
				        <tr>
				        	<th class="span1">Código</th>
				           	<th class="span4">Nome</th>
							<th class="span7">Descrição</th>
							<th>Opções</th>
				        </tr>
				    </thead>
				    <tbody>
				        <tr>
				            <td colspan="4">Carregando do servidor</td>
				        </tr>
				    </tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<a class="btn-large btn-primary" href="<?php echo $this->url('product', array('action'=>'add'));?>">Cadastrar</a>

<script>
	var URL = '<?php echo $this->serverUrl() . "/product"; ?>';
	ResultSet.paginate(URL);
</script>
